schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedFargateServiceInput"

  types:
    LoadBalancedFargateServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        desired_count:
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        subnet_type:
          type: string
          description: "Subnet type for your service"
          enum: ["public", "private"]
          default: "public"
        loadbalancer_type:
          type: string
          description: "Type of loadbalancer to front your service"
          enum: ["application", "network"]
          default: "application"
        image:
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/z9d2n7e1/nginx:1.21.0"
          minLength: 1
          maxLength: 200
        backendurl:
          type: string
          description: "Service discovery url of the backend service"
          default: "backend-svc-inst.backend-svc.fargate-env.local:80"
          minLength: 1
          maxLength: 200
